SELECT SKU, SKU_DESCRIPTION FROM INVENTORY;
SELECT SKU_DESCRIPTION, SKU FROM INVENTORY;
SELECT WarehouseID FROM INVENTORY;
SELECT WarehouseID FROM INVENTORY WHERE WarehouseID = 400;
SELECT WarehouseID, SKU, SKU_Description, QuantityOnHand, QuantityOnOrder FROM INVENTORY;
SELECT * FROM INVENTORY;
SELECT QuantityOnHand FROM INVENTORY WHERE QuantityOnHand > 0;
SELECT SKU, SKU_Description, QuantityOnHand FROM INVENTORY WHERE QuantityOnHand = 0;
SELECT SKU, SKU_Description, WarehouseID, QuantityOnHand FROM INVENTORY WHERE QuantityOnHand = 0 ORDER BY WarehouseID;
SELECT SKU, SKU_Description, WarehouseID, QuantityOnHand FROM INVENTORY WHERE QuantityOnHand > 0 ORDER BY SKU, WarehouseID DESC;
SELECT SKU, SKU_Description, WarehouseID FROM INVENTORY WHERE QuantityOnHand = 0 AND QuantityOnOrder > 0 ORDER BY SKU, WarehouseID DESC;
SELECT SKU, SKU_Description, WarehouseID FROM INVENTORY WHERE QuantityOnHand = 0 OR QuantityOnOrder > 0 ORDER BY SKU, WarehouseID DESC;
SELECT SKU, SKU_Description, WarehouseID FROM INVENTORY WHERE QuantityOnHand > 1 AND QuantityOnHand < 10;
SELECT SKU, SKU_Description, WarehouseID, QuantityOnHand FROM INVENTORY WHERE QuantityOnHand BETWEEN 2 AND 10;
SELECT SKU, SKU_Description FROM INVENTORY WHERE SKU_Description LIKE 'Half-Dome%';
SELECT SKU, SKU_Description FROM INVENTORY WHERE SKU_Description LIKE '%Climb%';
SELECT SKU, SKU_Description FROM INVENTORY WHERE SUBSTRING(SKU_Description, 3, 1) = 'd';
SELECT QuantityOnHand  FROM INVENTORY;
SELECT QuantityOnHand  FROM INVENTORY  WHERE QuantityOnHand > 100;
SELECT QuantityOnHand  FROM INVENTORY  WHERE QuantityOnHand < 100;
SELECT QuantityOnHand  FROM INVENTORY  WHERE QuantityOnHand = 100;
SELECT QuantityOnHand  FROM INVENTORY  WHERE QuantityOnHand = 100 OR 200;
SELECT COUNT(QuantityOnHand) FROM INVENTORY;
SELECT SUM(QuantityOnHand) FROM INVENTORY;
SELECT MAX(QuantityOnHand) FROM INVENTORY;
SELECT MIN(QuantityOnHand) FROM INVENTORY;
SELECT AVG(QuantityOnHand) FROM INVENTORY;
SELECT WarehouseID, SUM(QuantityOnHand) AS TotalItemsOnHand FROM INVENTORY GROUP BY WarehouseID ORDER BY TotalItemsOnHand DESC;
SELECT WarehouseID, SUM(QuantityOnHand) AS TotalItemsOnHandLT3 FROM INVENTORY WHERE QuantityOnHand < 3 GROUP BY WarehouseID ORDER BY TotalItemsOnHandLT3 DESC;
SELECT WarehouseID, SUM(QuantityOnHand) AS TotalItemsOnHandLT3 FROM INVENTORY WHERE QuantityOnHand < 3 GROUP BY WarehouseID HAVING COUNT(SKU) < 2 ORDER BY TotalItemsOnHandLT3 DESC;
